### ISSUE TITLE
垃圾sdk！！！

### ISSUE THREAD

**Issue by kadisting** [pili-engineering/PLDroidShortVideo#134]
保存视频段失败8！这么明显的bug，居然从1.2到1.6版本一直存在！！！你们发布的sdk不用测试的吗？退出录制视频的界面，再次进来仍然是失败！必须完全退出应用杀死进程。再次进来才可以，这也太垃圾了的吧，真不知道你的sdk里面做了什么垃圾操作。

**Comment by farsunset** [comment]
楼主 我已经找到原因并解决了此问题，可以联系我

**Comment by KevinHuo** [comment]
@kadisting 错误码 8 的原因是因为没有授权。可以联系下我们商务，申请授权哈～

**Comment by kadisting** [comment]
@farsunset 谢谢，我已经解决了。七牛真的恶心，发个sdk也不说明要授权，就在那报code8的错误，还以为是sdk的bug。看了一下最新版2.0.0的已经明确的把授权写出来了。程序员何必为难程序员呢，一个反射所有问题搞定！授权？呵呵~~~
