### ISSUE TITLE
垃圾sdk

### ISSUE THREAD

**Issue by cuibg** [pili-engineering/PLDroidShortVideo#150]
花钱买的用的，结果sdk那么垃圾，api都没有详细说明，第二，很多api用的时候需要的条件也没有说明，第三，我翻看源码，发现竟然有内存泄露，而且很多

**Comment by Johnny1994** [comment]
@cuibg 您好，关于您反馈的这些问题，能否举一些详细的例子呢？我们会根据您反馈的情况，对 SDK 做进一步的优化的
