### ISSUE TITLE
图片合成视频out of memery

### ISSUE THREAD

**Issue by dyz1990** [pili-engineering/PLDroidShortVideo#158]
大概有100张图片，合成视频的时长大概有120s，但在90s左右gpu开始报out of memery,生成的视频从90s后面开始全是黑屏。AS Profiler里可以看到Graphics占用的内存已达到1G，所有你们是把图片都上传到GPU，没有release吗？

**Comment by Johnny1994** [comment]
@dyz1990 感谢您的反馈，经验证，确实存在这样的问题，我们会在后续的版本进行修复，再次感谢~

**Comment by ShaoLongFei** [comment]
已修复
