### ISSUE TITLE
PLShortVideoEditor保存不支持软编？

### ISSUE THREAD

**Issue by dyz1990** [pili-engineering/PLDroidShortVideo#164]
硬编虽然速度快，但是保存的视频质量很差，文件大小也比软编大。想用软编，发现设置PLVideoEncodeSetting.setHWCodecEnabled(true)没用，
反编译源码可以看到代码里是直接new了一个HWVideoEncoder，没有使用PLVideoEncodeSetting里的设置。
不知道什么时候可以支持用软编？

**Comment by ShaoLongFei** [comment]
目前不支持
