### ISSUE TITLE
华为手机 nova 5i Pro 录制视频报错,缺少libpldroid_shortvideo_core.so 64位的

### ISSUE THREAD

**Issue by PrinceIce10** [pili-engineering/PLDroidShortVideo#180]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
[DexPathList[[zip file "/data/app/com.cheyw.youlong-8_GL0iJVAJKzmOitJQtMpg==/base.apk"],
nativeLibraryDirectories=[/data/app/com.cheyw.youlong-8_GL0iJVAJKzmOitJQtMpg==/lib/arm64, 
/data/app/com.cheyw.youlong-8_GL0iJVAJKzmOitJQtMpg==/base.apk!/lib/arm64-v8a, /system/lib64, 
/product/lib64]]] couldn't find "libpldroid_shortvideo_core.so"

**Comment by PrinceIce10** [comment]
SDK里没有libpldroid_shortvideo_core.so, DEMO里只有 armeabi-v7a 的.

**Comment by PrinceIce10** [comment]
解压缩文件损坏了

**Comment by xiaoalan** [comment]
解决了吗
