### ISSUE TITLE
拼接视频段失败：8

### ISSUE THREAD

**Issue by junge89221** [pili-engineering/PLDroidShortVideo#20]
现象：录制视频完成后，点击√进入下一步出现。这个是随机性的出现，视频不管录制了一段和多段，都会出现拼接视频段失败：8的错误，必须要关闭app，杀掉进程再进入下一步！

**Comment by Jhuster** [comment]
@junge89221 本 SDK 需要授权才能使用，请参考首页 README 联系获取授权

**Comment by as570303** [comment]
你好，我这边稍微改了下让他点击之后自己录制 然后当他达到总时长我调用保存方法，结果每次都是拼接字段失败：1的错误，百分百必现 这是怎么回事？

**Comment by Jhuster** [comment]
@as570303 的确是个 BUG，下一个版本修复，多谢反馈

**Comment by junge89221** [comment]
@Jhuster 请问下一版什么时候发呢？拼接字段失败：1这个bug比较紧急~~

**Comment by Jhuster** [comment]
@junge89221 这两天，目前你可以先调用 endSection 再调用 concat 试试

**Comment by junge89221** [comment]
@Jhuster 可用··谢谢··

**Comment by junge89221** [comment]
@Jhuster 先调用 endSection 再调用 concat这个方式发现一个BUG，假如从下一个界面返回上一个界面继续拼接录制视频自动保存，会报拼接字段失败：1，100%出现；

**Comment by Jhuster** [comment]
@junge89221 试试 1.3.0 ，已发布

**Comment by af913337456** [comment]
@Jhuster 这个问题有解决方案了吗？“先调用 endSection 再调用 concat 试试” 会导致闪退。native 层闪退。

**Comment by af913337456** [comment]
@Jhuster  小米note2

**Comment by af913337456** [comment]
@Jhuster  补充一下，出现一次 8 错误后，之后的都是上面的闪退，十分神奇，重装也是一样

**Comment by af913337456** [comment]
1 #00    pc 0002bc24    /data/app/com.accurme.normaluser-2/lib/arm/libpldroid_shortvideo_core.so [armeabi-v7a]
--
2 java:
3 com.qiniu.pili.droid.shortvideo.muxer.FFMP4Muxer.a(FFMP4Muxer.java:145)
4 com.qiniu.pili.droid.shortvideo.muxer.a.a(MP4Muxer.java:43)
5 com.qiniu.pili.droid.shortvideo.b.c.g(SectionManager.java:326)
6 com.qiniu.pili.droid.shortvideo.b.c$1.run(SectionManager.java:253)
7 java.lang.Thread.run(Thread.java:818)

**Comment by af913337456** [comment]
@Jhuster  fixed 了,请 close

**Comment by Jhuster** [comment]
@af913337456 是指升级到新版后没有出现了吗

**Comment by af913337456** [comment]
@Jhuster  非也，个人造成，无需再关注

**Comment by cuibg** [comment]
保存个视频也需要授权？
