### ISSUE TITLE
对接FaceUnity时遇到的问题

### ISSUE THREAD

**Issue by TuJHgithub** [pili-engineering/PLDroidShortVideo#21]
1. onSurfaceCreated回调第一行就执行checkGlError，LOG打印出glError 0x501。是否在七牛SDK中就存在glError（不影响正常流程）。
 2. 在demo中mCameraSetting.getCameraId()返回的cameraId永远是1，是否有api能够获取cameraId?
 3. onPreviewFrame回调中，使用前置摄像头或后置摄像头返回的视频角度参数（顺时针 0/90/180/270 度）是不变的，而实际上byte[]画面的方向并不一样。
 4. onDrawFrame回调中返回的texture是经过处理的，有没有回调可以直接返回OES的texture？

**Comment by geeklok** [comment]
1. 经过检查的确有 0x501，下个版本会处理。
2. 目前 CameraSetting 里的 cameraId 不会根据摄像头切换而改变，这个后面可以考虑增加获取的方式。
3. 这个经查实是内部的 bug，下个版本会处理。
4. 目前没有回调 OES 纹理的接口，请问这个需求的目的是？

**Comment by TuJHgithub** [comment]
4. 对接faceunity时，faceunity使用的是双输入的方式来处理画面，因此对于现在接口回调的纹理就与byte[]的画面方向不一致，就需要把纹理变换回OES纹理相同的方向才能正常使用。而这些变换都是多余的，不太清除你们为什么要把OES纹理经过处理后再给回调，这样不是消耗了性能也降低了通用性嘛？

**Comment by Jhuster** [comment]
@TuJHgithub 新版已经支持回调 OES 纹理
