### ISSUE TITLE
拼接视频段失败：8

### ISSUE THREAD

**Issue by jsoncoco** [pili-engineering/PLDroidShortVideo#35]
而且我是授权后使用的，请问这是怎么回事？我的版本是1.4.0，概率性出现，需要杀死app进程，再次进入，才可以。

**Comment by jsoncoco** [comment]
我的版本是1.4.0

**Comment by Jhuster** [comment]
@jsoncoco 包名发出来下

**Comment by jsoncoco** [comment]
com.snooker.activity

**Comment by Jhuster** [comment]
@jsoncoco 确定你的包名含有 `.activity` 吗，实际的包名会不会给错了，看看 `manifest` 里面定义的 `package`

**Comment by jsoncoco** [comment]
![image](https://user-images.githubusercontent.com/17939823/30532136-37e97d38-9c85-11e7-9db0-6ba8b570f030.png)

**Comment by jsoncoco** [comment]
我只录制一段视频，没有分段的，就会概率性出现这个问题，机型为小米4，系统为android6.0.1，我自己感觉这个跟机型没什么关系，我小米3的也出现这个问题。

**Comment by Jhuster** [comment]
@jsoncoco 再出现 8 的错误，给出具体的日期时间点，我们查下服务端日志

**Comment by jsoncoco** [comment]
在2到3分钟前，就有一次，出现这个问题。

**Comment by Jhuster** [comment]
@jsoncoco 抱歉，是我们这边把你们的包名配置错误导致的，已改好

**Comment by jsoncoco** [comment]
视频的水印大小是由什么控制的？根据设计工程师的图片尺寸吗？代码能设置吗？我在源码里面没有找到，能提示一下吗？大佬！

**Comment by Jhuster** [comment]
@jsoncoco 建议另起 issue 来讨论，不过这个先这样吧，水印直接用的是传入的图的大小，没有做缩放和剪裁，这样省功耗，建议美工切一下合适的大小

**Comment by jsoncoco** [comment]
好的，谢谢
