### ISSUE TITLE
预览的清晰度能否做到和系统拍照时候的一样？

### ISSUE THREAD

**Issue by af913337456** [pili-engineering/PLDroidShortVideo#48]
@Jhuster

**Comment by Jhuster** [comment]
@af913337456 当然可以，保持跟系统拍照参数一致即可

**Comment by af913337456** [comment]
全屏，预览比例 16：9，预览分辨率看到SDK内部最高是 1200P，1200 目前还达不到相机清晰度。是否可以自定义传入？ @Jhuster

**Comment by geeklok** [comment]
@af913337456 可以通过 PLShortVideoRecorder.setCameraParamSelectListener(PLCameraParamSelectListener) 设置相机相关的参数，其中 PLCameraParamSelectListener.onPreviewSizeSelected(List<Camera.Size>) 可以选择当前摄像头的预览分辨率。
