### ISSUE TITLE
我司产品不是做直播的 如果用这个 如何收费呢？

### ISSUE THREAD

**Issue by xiaolongyuan** [pili-engineering/PLDroidShortVideo#5]

**Comment by Jhuster** [comment]
@xiaolongyuan 参考 README，`可通过 400-808-9176 转 2 号线联系七牛商务咨询，或者 通过工单 联系七牛的技术支持。`

**Comment by xiaolongyuan** [comment]
问了一下 授权费8w ....

**Comment by alwaysmavs** [comment]
有比较多的商务套餐的，最近应该有充值活动，你这边何对应的商务再沟通下。
