### ISSUE TITLE
录制的视频 右下角有绿色方块闪现

### ISSUE THREAD

**Issue by zxy198717** [pili-engineering/PLDroidShortVideo#8]
见图:

![screenshot_20170731-095101](https://user-images.githubusercontent.com/785333/28760117-ab9c6504-75d6-11e7-989c-29fcc504f3f6.png)

**Comment by Jhuster** [comment]
@zxy198717 请问是什么机型？

**Comment by zxy198717** [comment]
@Jhuster 荣耀Note8 android7.0的系统

**Comment by Jhuster** [comment]
@zxy198717 收到，该机型以及华为部分机型的绿块问题已在跟进中

**Comment by Jhuster** [comment]
@zxy198717 请更新到 v1.2.1 版本，该问题已修复
